/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial;

import tutorial.Gui.Gui;

public class App {
    public String getGreeting() {
        return "Carlos Zavala Quick test";// Test comment
    }

    public static void main(String[] args) {
        Gui.startGui();
    }
}
